# I kind of prefer the flutter lints, so use it for now,
# instead of manually copying it over 🤷️

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: false

    # TODO: rename constants.
    constant_identifier_names: false

    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    unsafe_html: true

    always_put_control_body_on_new_line: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_slow_async_io: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    directives_ordering: true
    no_adjacent_strings_in_list: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true

formatter:
  trailing_commas: preserve
